---
title: "Discussion 2: Hack-a-thon Animated Visualizations"
author: "Andrea Gonzalez"
team: "Bull Theory"
output: html_notebook
---

# Load Libraries
```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(tidyverse)
library(ggplot2)
library(png)
# install.packages("gifski")
library(gifski)
library(gapminder)
library(gganimate)
library(scales)
library(lubridate)
# install.packages("hrbrthemes")
library(hrbrthemes)
```
stringsAsFactors = T

# Load data
```{r}
cryptoData<- read.csv("~/Downloads/Crypto_Hackathon_BullTheory.csv")
cryptoData
```

# Summarize and clean data
```{r}
summary(cryptoData)
```
  
```{r}
cryptoData1 <- cryptoData %>%
  mutate(NewDate = as.Date(cryptoData$date, format = "%m/%d/%y")) %>% 
    mutate(Profit = total - lag(x = total, n = 1), 
        Flag = case_when(
            Profit > 0 ~ "Gain", 
            Profit == 0 ~ "Neither", 
            Profit < 0 ~ "Loss"))
cryptoData1
```

```{r}
cryptoData2 <- cryptoData1 %>% select(username, cash, total, NewDate, Profit, Flag)
cryptoData2
```
 

# Visualizations

## Fig 1: Profit Variance according to total crypto price
```{r}
Fig1 <- ggplot(data = cryptoData2, mapping = aes(x = NewDate, y = total)) + 
    geom_line(mapping = aes(y = Profit), color = "red") +
    theme_bw() +
    theme(axis.text.x = element_text(face = "bold", size = 10, angle = 90)) +
    theme(axis.text.y = element_text(face = "bold", size = 10)) +
    transition_reveal(NewDate)+
    labs(title = "Hackathon 2021: Profit Variance according to total crypto price",
         subtitle = "Team: Bull Theory",
         x = "Date",
         y = "Total Cash",
         caption = "Source: Crypto Hackathon 2021 - Bull Theory Team")
Fig1

animate(Fig1, height = 800, width =800)
anim_save("CHackathon 2021: Profit Variance within total coin price Fig1.gif")
```

### Remove NA's for Fig2
```{r}
cryptoData3 <- na.omit(cryptoData2)
cryptoData3
```

## Fig 2: Total cash vs. Profit
```{r}
Fig2 <- cryptoData3 %>% ggplot() + 
    geom_point(aes(x = NewDate, y = Profit, colour = Flag), alpha = 0.8) + 
    theme_minimal() + 
    theme(legend.position = "bottom") + 
    transition_time(NewDate) +
    labs(title = "Hackathon 2021: Total cash vs. Profit",
         subtitle = "Team: Bull Theory",
         x = "Date",
         y = "Total Cash",
         caption = "Source: Crypto Hackathon 2021 - Bull Theory Team")
Fig2

animate(my.animation, height = 800, width =800)
anim_save("CHackathon 2021: Profit Variance within total coin price Fig1.gif")
```


## Fig 3: Profit Flow (Gain, Loss or Null) according to total cash and profit records
```{r}
Fig3 <- cryptoData2 %>% ggplot(gapminder, mapping = aes(NewDate, total, size = Profit, colour = Flag)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_size(range = c(2,12)) +
  #here comes the gganimate specific bits
 labs(title = "Hackathon 2021: Profit Flow",
         subtitle = "Team: Bull Theory",
         x = "Date",
         y = "Total Cash",
         caption = "Source: Crypto Hackathon 2021 - Bull Theory Team") +
  transition_time(NewDate) +
  ease_aes('cubic-in-out')
Fig3

animate(my.animation, height = 800, width =800)
anim_save("CHackathon 2021: Profit Variances Fig3.gif")
```

## Fig 4: Gain, Loss or Null cash flow results according to the profit made
```{r}
Fig4 <- cryptoData2 %>% ggplot(mapping = aes(x = Flag, y = Profit, fill = Flag)) + 
    geom_col() +
    theme_bw() +
    theme(axis.text.x = element_text(face = "bold", size = 10)) +
    theme(axis.text.y = element_text(face = "bold", size = 10)) +
    transition_states(NewDate,
    transition_length = 1,
    state_length = 2) +
    enter_fade()
    labs(title = "Hackathon 2021:  Gain, Loss or Null Cash Flow",
         subtitle = "Team: Bull Theoryy",
         x = "Gain, Loss, Null",
         y = "Total Profit",
         caption = "Source: Crypto Hackathon 2021 - Bull Theory Team")
Fig4

animate(my.animation, height = 800, width =800)
anim_save("CHackathon 2021: Profit Variances Fig3.gif")
```
